### ISSUE TITLE
Can't install: cannot find type `EventFilter` in this scope

### ISSUE THREAD

**Issue by tobymurray** [VerKnowSys/lw#1]
Not sure if you're intending this for public consumption but, I tried installing this today on Ubuntu 22.04.1 LTS with:

```
$ rustc --version
rustc 1.65.0 (897e37553 2022-11-02)
```
and it failed to install:
```
$ cargo install lw
    Updating crates.io index
  Installing lw v0.6.10
   Compiling libc v0.2.138
   Compiling proc-macro2 v1.0.47
   Compiling autocfg v1.1.0
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.105
   Compiling serde_derive v1.0.150
   Compiling cc v1.0.77
   Compiling lazy_static v1.4.0
   Compiling serde v1.0.150
   Compiling log v0.4.17
   Compiling cfg-if v1.0.0
   Compiling bitflags v0.7.0
   Compiling iana-time-zone v0.1.53
   Compiling bitflags v1.3.2
   Compiling same-file v1.0.6
   Compiling base64 v0.13.1
   Compiling walkdir v2.3.2
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling libmimalloc-sys v0.1.28
   Compiling atty v0.2.14
   Compiling time v0.1.45
   Compiling kqueue2-sys v0.1.5
   Compiling colored v1.9.3
   Compiling colored v2.0.0
error[E0412]: cannot find type `EventFilter` in this scope
  --> /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/kqueue2-sys-0.1.5/src/lib.rs:25:17
   |
25 |     pub filter: EventFilter,
   |                 ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `EventFlag` in this scope
  --> /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/kqueue2-sys-0.1.5/src/lib.rs:26:16
   |
26 |     pub flags: EventFlag,
   |                ^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `FilterFlag` in this scope
  --> /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/kqueue2-sys-0.1.5/src/lib.rs:27:17
   |
27 |     pub fflags: FilterFlag,
   |                 ^^^^^^^^^^ not found in this scope
```

**Comment by dmilith** [comment]
It's likely that this project will not work on systems without the "kqueue" feature, but you may try with proxy libraries like https://manpages.ubuntu.com/manpages/xenial/man2/kqueue.2.html

To make it work I'll likely have to add a Linux-specific linker option (`-lkqueue`?) for the LW project. I can do that if you can test it and confirm this works on your system :)

**Comment by dmilith** [comment]
Ok, I already noticed that Linux is also not supported by the kqueue2 crate (yet): https://github.com/VerKnowSys/rust-kqueue-sys/tree/master/src/constants

**Comment by dmilith** [comment]
Since I also maintain the "kqueue2" and "kqueue2-sys" crates (which I forked), you could define linux.rs with values based on https://github.com/VerKnowSys/rust-kqueue-sys/blob/master/src/constants/freebsd.rs and then I can add Linux support.

**Comment by tobymurray** [comment]
I guess trying to pursue kqueue tooling on a Debian system is a bit of a round-about way to go - seems like maybe I should look at epoll and ultimately inotify based crates?

**Comment by dmilith** [comment]
@tobymurray LW project was based on kqueue, which exists only on BSDs and Macs. Sorry :)

**Comment by tobymurray** [comment]
No worries - that clears it up for me. I truly know very little about what I'm doing, and was surprised to see an error doing a `cargo install`. Thanks for the quick response!
